teamtemp/urls.py
import cspreports.urls
from django.conf import settings
from django.urls import include, re_path
from django.contrib import admin as djadmin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.views.static import serve as serve_static
from rest_framework import routers
from rest_framework.documentation import include_docs_urls


from teamtemp.views import TeamResponseHistoryViewSet, TeamTemperatureViewSet, TeamsViewSet, TemperatureResponseViewSet, \
    UserViewSet, WordCloudImageViewSet, admin_view, bvc_view, cron_view, health_check_view, home_view, \
    media_view, reset_view, robots_txt_view, set_view, submit_view, team_view, user_view, wordcloud_view, login_view, \
    super_view

router = routers.DefaultRouter()
router.register(r'word_cloud_images', WordCloudImageViewSet)
router.register(r'users', UserViewSet)
router.register(r'team_temperatures', TeamTemperatureViewSet)
router.register(r'temperature_responses', TemperatureResponseViewSet)
router.register(r'team_response_histories', TeamResponseHistoryViewSet)
router.register(r'teams', TeamsViewSet)

urlpatterns = [
    re_path(r'^cs$', home_view, {'survey_type': 'CUSTOMERFEEDBACK'}),
    re_path(r'^drs$', home_view, {'survey_type': 'DEPT-REGION-SITE'}),
    re_path(r'^$', home_view, name='home'),
    re_path(r'^about$', TemplateView.as_view(template_name='about.html'),
        name='about'),
    re_path(r'^user/?$', user_view, name='user'),
    re_path(r'^super/(?P<survey_id>[0-9a-zA-Z]{8})/?$', super_view, name='super'),
    re_path(r'^super/(?P<survey_id>[0-9a-zA-Z]{8})(?P<redirect_to>/.+)$', super_view, name='super'),
    re_path(r'^admin/(?P<survey_id>[0-9a-zA-Z]{8})/?$', admin_view, name='admin'),
    re_path(r'^login/(?P<survey_id>[0-9a-zA-Z]{8})/?$', login_view, name='login'),
    re_path(r'^login/(?P<survey_id>[0-9a-zA-Z]{8})(?P<redirect_to>/.+)$', login_view, name='login'),
    re_path(r'^set/(?P<survey_id>[0-9a-zA-Z]{8})/?$', set_view, name='set'),
    re_path(r'^admin/(?P<survey_id>[0-9a-zA-Z]{8})/(?P<team_name>[-\w]{1,64})/?$', admin_view, name='admin'),
    re_path(r'^(?P<survey_id>[0-9a-zA-Z]{8})/(?P<team_name>[-\w]{1,64})$', submit_view, name='submit'),

    re_path(r'^bvc/(?P<survey_id>[0-9a-zA-Z]{8})/?$', bvc_view, name='bvc'),
    re_path(r'^bvc/(?P<survey_id>[0-9a-zA-Z]{8})/i(?P<num_iterations>[0-9]{1,3})$', bvc_view, name='bvc'),
    re_path(r'^bvc/(?P<survey_id>[0-9a-zA-Z]{8})/(?P<team_name>[-\w]{1,64})/i(?P<num_iterations>[0-9]{1,3})$', bvc_view,
        name='bvc'),
    re_path(r'^bvc/(?P<survey_id>[0-9a-zA-Z]{8})/(?P<archive_id>[0-9]{1,20})/?$', bvc_view, name='bvc'),
    re_path(r'^bvc/(?P<survey_id>[0-9a-zA-Z]{8})/(?P<team_name>[-\w]{1,64})/?$', bvc_view, name='bvc'),
    re_path(r'^bvc/(?P<survey_id>[0-9a-zA-Z]{8})/(?P<team_name>[-\w]{1,64})/(?P<archive_id>[0-9]{1,20})/?$', bvc_view,
        name='bvc'),

    re_path(r'^bvc/(?P<survey_id>[0-9a-zA-Z]{8})/region=(?P<region_names>[-\w\,]{1,64})/?$', bvc_view, name='bvc'),
    re_path(r'^bvc/(?P<survey_id>[0-9a-zA-Z]{8})/site=(?P<site_names>[-\w\,]{1,64})/?$', bvc_view, name='bvc'),
    re_path(r'^bvc/(?P<survey_id>[0-9a-zA-Z]{8})/dept=(?P<dept_names>[-\w\,]{1,64})/?$', bvc_view, name='bvc'),

    re_path(
        r'^bvc/(?P<survey_id>[0-9a-zA-Z]{8})/(?P<archive_id>[0-9]{1,20})/dept=(?P<dept_names>[-\w\,]{0,64})/region=(?P<region_names>[-\w\,]{0,64})/site=(?P<site_names>[-\w\,]{0,64})$',
        bvc_view, name='bvc'),
    re_path(
        r'^bvc/(?P<survey_id>[0-9a-zA-Z]{8})/dept=(?P<dept_names>[-\w\,]{0,64})/region=(?P<region_names>[-\w\,]{0,64})/site=(?P<site_names>[-\w\,]{0,64})$',
        bvc_view, name='bvc'),

    re_path(r'^bvc/(?P<survey_id>[0-9a-zA-Z]{8})/(?P<archive_id>[0-9]{1,20})/region=(?P<region_name>[-\w\,]{1,64})/?$',
        bvc_view,
        name='bvc'),
    re_path(r'^bvc/(?P<survey_id>[0-9a-zA-Z]{8})/(?P<archive_id>[0-9]{1,20})/site=(?P<site_name>[-\w\,]{1,64})/?$', bvc_view,
        name='bvc'),
    re_path(r'^bvc/(?P<survey_id>[0-9a-zA-Z]{8})/(?P<archive_id>[0-9]{1,20})/dept=(?P<dept_name>[-\w\,]{1,64})/?$', bvc_view,
        name='bvc'),

    re_path(r'^reset/(?P<survey_id>[0-9a-zA-Z]{8})/?$', reset_view, name='reset'),
    re_path(r'^cron/(?P<pin>.{4,100})$', cron_view, name='cron'),
    re_path(r'^team/(?P<survey_id>[0-9a-zA-Z]{8})/(?P<team_name>[-\w]{1,64})$', team_view, name='team'),
    re_path(r'^team/(?P<survey_id>[0-9a-zA-Z]{8})/?$', team_view, name='team'),
    re_path(r'^wordcloud/(?P<word_hash>[a-f0-9]{40})?$', wordcloud_view, name='wordcloud'),
    re_path(r'^wordcloud/(?P<width>[1-9][0-9]{2,3})x(?P<height>[1-9][0-9]{2,3})/(?P<word_hash>[a-f0-9]{40})?$', wordcloud_view,
        name='wordcloud'),
    re_path(r'^static/(.*)$', serve_static, {'document_root': settings.STATIC_ROOT}, name='static'),
    re_path(r'^media/(.*)$', media_view, {'document_root': settings.MEDIA_ROOT}, name='media'),
    re_path(r'^healthcheck/?$', health_check_view, name='healthcheck'),
    re_path(r'^robots\.txt', robots_txt_view, name='robots_txt'),
    re_path(r'^favicon\.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')), name='favicon'),
    re_path(r'^djadmin/', djadmin.site.urls),
    re_path(r'^api/', include(router.urls)),
    re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'^docs/', include_docs_urls(title='Team Temperature API')),
    re_path(r'^csp/', include('cspreports.urls')),
]

teamtemp/responses/models.py
from __future__ import unicode_literals

import hashlib
from datetime import timedelta

import pytz
from builtins import object
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone


class WordCloudImage(models.Model):
    class Meta(object):
      unique_together = ("word_hash", "width", "height")

    id = models.AutoField(primary_key=True)
    word_hash = models.CharField(max_length=40)
    word_list = models.CharField(max_length=5000)
    width = models.PositiveSmallIntegerField(null=True, blank=True)
    height = models.PositiveSmallIntegerField(null=True, blank=True)
    image_url = models.CharField(max_length=255, null=True, blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True, db_index=True)

    def __str__(self):
        return "{}: {} {} {} {} {} {}".format(
            self.id,
            self.creation_date,
            self.word_hash,
            self.width,
            self.height,
            self.word_list,
            self.image_url)

    def clean(self):
        self.word_list = self.word_list.lower().strip()
        self.word_hash = hashlib.sha1(
            self.word_list.encode('utf-8')).hexdigest()


class User(models.Model):
    id = models.CharField(max_length=32, primary_key=True)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}: {}".format(self.id, self.creation_date)


def _stats_for(query_set):
    return {
        'count': query_set.count(), 'average': query_set.aggregate(
            models.Avg('score')), 'minimum': query_set.aggregate(
            models.Min('score')), 'maximum': query_set.aggregate(
                models.Max('score')), 'words': query_set.values('word').annotate(
                    models.Count("id")).order_by()}, query_set


class TeamTemperature(models.Model):
    TEAM_TEMP = 'TEAMTEMP'
    DEPT_REGION_SITE = 'DEPT-REGION-SITE'
    CUSTOMER_FEEDBACK = 'CUSTOMERFEEDBACK'

    SURVEY_TYPE_CHOICES = (
        (TEAM_TEMP, 'Team Temperature'),
        (DEPT_REGION_SITE, 'Department-Region-Site Temperature'),
        (CUSTOMER_FEEDBACK, 'Customer Feedback'),
    )

    TIMEZONE_CHOICES = [(tz, tz) for tz in pytz.all_timezones]

    id = models.CharField(max_length=8, primary_key=True)
    creator = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        related_name="team_temperatures")
    password = models.CharField(max_length=256)
    archive_schedule = models.PositiveSmallIntegerField(default=0)
    archive_date = models.DateTimeField(blank=True, null=True)
    next_archive_date = models.DateField(blank=True, null=True)
    survey_type = models.CharField(
        default=TEAM_TEMP,
        choices=SURVEY_TYPE_CHOICES,
        max_length=20,
        db_index=True)
    dept_names = models.CharField(blank=True, null=True, max_length=64)
    region_names = models.CharField(blank=True, null=True, max_length=64)
    site_names = models.CharField(blank=True, null=True, max_length=64)
    default_tz = models.CharField(
        default='Australia/Queensland',
        choices=TIMEZONE_CHOICES,
        max_length=64)
    max_word_count = models.PositiveSmallIntegerField(
        default=1, validators=[MinValueValidator(1), MaxValueValidator(5)])
    creation_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def stats(self):
        return _stats_for(self.temperature_responses.filter(archived=False))

    def team_stats(self, team_name_list):
        return _stats_for(
            self.temperature_responses.filter(
                team_name__in=team_name_list,
                archived=False))

    def archive_stats(self, archive_date):
        return _stats_for(
            self.temperature_responses.filter(
                archived=True,
                archive_date=archive_date))

    def archive_team_stats(self, team_name_list, archive_date):
        return _stats_for(
            self.temperature_responses.filter(
                team_name__in=team_name_list,
                archive_date=archive_date,
                archived=True))

    def accumulated_stats(self, start_date, end_date):
        return _stats_for(
            self.temperature_responses.filter(
                response_date__gte=end_date,
                response_date__lte=start_date))

    def accumulated_team_stats(self, team_name_list, start_date, end_date):
        return _stats_for(
            self.temperature_responses.filter(
                team_name__in=team_name_list,
                response_date__gte=end_date,
                response_date__lte=start_date))

    def fill_next_archive_date(self, overwrite=False):
        if self.archive_schedule > 0:
            if self.next_archive_date is None:
                if self.archive_date is not None:
                    self.next_archive_date = (
                        self.archive_date +
                        timedelta(
                            days=self.archive_schedule)).date()
                else:
                    self.next_archive_date = timezone.localtime(
                        timezone.now(), timezone=pytz.timezone(self.default_tz)).date()

        return self.next_archive_date

    def advance_next_archive_date(self, now_date=None):
        self.fill_next_archive_date()

        if self.archive_schedule > 0:
            if not now_date:
                now_date = timezone.localtime(
                    timezone.now(), timezone=pytz.timezone(
                        self.default_tz)).date()

            while self.next_archive_date <= now_date:
                self.next_archive_date = self.next_archive_date + \
                    timedelta(days=self.archive_schedule)

        return self.next_archive_date

    def __str__(self):
        return "{}: {} {} {} {} {} {} {} {} {}".format(
            self.id,
            self.creator.id,
            self.creation_date,
            self.archive_schedule,
            self.archive_date,
            self.survey_type,
            self.region_names,
            self.region_names,
            self.site_names,
            self.default_tz)


class TemperatureResponse(models.Model):
    # class Meta:
    #     unique_together = ("request", "responder", "team_name", "archive_date")

    id = models.AutoField(primary_key=True)
    request = models.ForeignKey(
        TeamTemperature,
        on_delete=models.CASCADE,
        related_name="temperature_responses")
    responder = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        related_name="temperature_responses")
    score = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(10)])
    word = models.CharField(max_length=32, db_index=True)
    team_name = models.CharField(max_length=64, db_index=True)
    archived = models.BooleanField(default=False, db_index=True)
    response_date = models.DateTimeField(db_index=True)
    archive_date = models.DateTimeField(blank=True, null=True, db_index=True)

    def pretty_team_name(self):
        return self.team_name.replace('_', ' ')

    def __str__(self):
        return "{}: {} {} {} {} {} {} {} {}".format(
            self.id,
            self.request.id,
            self.responder.id,
            self.score,
            self.word,
            self.team_name,
            self.archived,
            self.response_date,
            self.archive_date)

    def clean(self):
        self.word = self.word.lower().strip()


class TeamResponseHistory(models.Model):
    class Meta(object):
        verbose_name_plural = "Team response histories"

    id = models.AutoField(primary_key=True)
    request = models.ForeignKey(
        TeamTemperature,
        on_delete=models.CASCADE,
        related_name="team_response_histories")
    average_score = models.DecimalField(decimal_places=5, max_digits=10)
    minimum_score = models.PositiveSmallIntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(10)],
        null=True,
        blank=True)
    maximum_score = models.PositiveSmallIntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(10)],
        null=True,
        blank=True)
    word_list = models.CharField(max_length=5000)
    responder_count = models.PositiveSmallIntegerField()
    team_name = models.CharField(max_length=64, null=True, db_index=True)
    archive_date = models.DateTimeField(db_index=True)

    def pretty_team_name(self):
        return self.team_name.replace('_', ' ')

    def __str__(self):
        return "{}: {} {} {} {} {} {}".format(
            self.id,
            self.request.id,
            self.average_score,
            self.word_list,
            self.responder_count,
            self.team_name,
            self.archive_date)

    def clean(self):
        self.word_list = self.word_list.lower().strip()


class Teams(models.Model):
    class Meta(object):
        verbose_name = "Team"
        verbose_name_plural = "Teams"
        unique_together = ("request", "team_name")

    id = models.AutoField(primary_key=True)
    request = models.ForeignKey(
        TeamTemperature,
        on_delete=models.CASCADE,
        related_name="teams")
    team_name = models.CharField(max_length=64, db_index=True)
    dept_name = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        db_index=True)
    site_name = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        db_index=True)
    region_name = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        db_index=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def pretty_team_name(self):

teamtemp/templates/about.html
{% extends "base.html" %}

{% block title %}About Team Temperature{% endblock %}

{% block body %}
  <div class="container">
    <h1>About Team Temperature</h1>
    <p>
      This application is designed to gather 'team temperature' - that is,
      a happiness score.</p>

    <p>For the sake of security, very little information is stored or recorded.
      Each submitter is represented by a random ID, and a cookie is stored
      really only to protect against accidental double submissions from the
      same user, with the same browser.</p>

    <p>The results page are available to the creator using the same cookie
      mechanism, and also a password in case the cookie is lost.</p>

    <p>It is deployed at <a href="https://teamtempapp.herokuapp.com/">teamtempapp.herokuapp.com</a>
      hosted on <a href="https://heroku.com">Heroku</a> and the source for this version
      can be examined <a href="https://github.com/rloomans/new-teamtemp">on Github</a>.
      All reasonable pull requests will be considered, as will any issues raised.</p>

    <p>The application is written in <a href="https://www.djangoproject.com/">Django</a>
      against a <a href="https://www.postgresql.org/">PostgreSQL</a> database.</p>
  </div>
{% endblock %}

teamtemp/templates/admin.html
{% extends "base.html" %}

{{ form.errors }}

{% block title %}Team Temperature{% endblock %}

{% block body %}
<h1>Create a Team Temperature Survey</h1>
<form method="post">
  {% csrf_token %}
  <input class="btn btn-primary btn-lg" type="submit" value="Create"/>
</form>
{% endblock %}

teamtemp/templates/base.html
{% extends 'bootstrap3/bootstrap3.html' %}

{% load bootstrap3 %}
{% load static %}

{% block bootstrap3_title %}{% block title %}{% endblock %}{% endblock %}
{% block bootstrap3_extra_head %}
    <link rel="stylesheet" href="{% static "style.css" %}">
    <link rel="shortcut icon" href="{% static "favicon.ico" %}" type="image/x-icon">
    <link rel="icon" href="{% static "favicon.ico" %}" type="image/x-icon">
    {% block form_extra_head %}{% endblock %}
{% endblock %}

{% block bootstrap3_content %}
  {# Display django.contrib.messages as Bootstrap alerts #}
  {% autoescape off %}<div class="container">{% bootstrap_messages %}</div>{% endautoescape %}
  {% block body %}{% endblock %}
  {% block footer %}
    <div class="footer no-print"><p><br><br><a href="{% url "about" %}">About this site</a> <a href="/djadmin/">•</a> <a href="{% url "user" %}">Current user</a></p></div><br><br><br>
  {% endblock %}
  {% if GOOGLE_ANALYTICS_PROPERTY_ID %}{% include "ga.html" %}{% endif %}
{% endblock %}

teamtemp/templates/form.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}{{ pretty_team_name }} {{ survey_type_title }}{% endblock %}

{% block body %}

  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <br>
        <!--[if !IE]> -->
        <a href="{% url 'bvc' survey_id=id team_name=team_name %}" class="btn btn-primary">BVC</a>
        <!-- <![endif]-->

        <h1>{{ pretty_team_name }} {{ survey_type_title }}</h1>
        <h2>Submit your {{ survey_type_title }}</h2>
        <form method="post">
          {% csrf_token %}

          {% if response_id %}
            <input type="hidden" name="id" value="{{ response_id }}"/>
          {% endif %}

          {% bootstrap_form_errors form type='non_fields' %}

          {{ temp_question_title }}
          <div class="row">
            <div class="col-md-6">
              {% bootstrap_field form.score layout='vertical' size='sm' show_label=False %}
            </div>
          </div>

          {{ word_question_title }}
          <div class="row">
            <div class="col-md-6">
              {% bootstrap_field form.word layout='vertical' size='sm' show_label=False %}
            </div>
          </div>

          {% buttons %}
            {% bootstrap_button "Submit" button_type="submit" button_class="btn-primary" %}
          {% endbuttons %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

teamtemp/templates/index.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}Create Team Temperature{% endblock %}

{% block body %}

  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">

        <h1>Create a Team Temperature Survey</h1>

        <div class="field">
          <label for="id_survey_type">Select Survey Type</label><br>
          <select id="id_survey_type" name="survey_type" required="">
            <option value="TEAMTEMP" {% if not survey_type or survey_type == "TEAMTEMP" %}selected{% endif %}>Team Temperature</option>
            <option value="DEPT-REGION-SITE" {% if survey_type == "DEPT-REGION-SITE" %}selected{% endif %}>Department-Region-Site Temperature</option>
            <option value="CUSTOMERFEEDBACK" {% if survey_type == "CUSTOMERFEEDBACK" %}selected{% endif %}>Customer Feedback</option>
          </select>
          <script>
            document.getElementById("id_survey_type").onchange = function () {
              if (this.value == 'DEPT-REGION-SITE') {
                window.location.href = "/drs"
              }
              else if (this.value == 'CUSTOMERFEEDBACK') {
                window.location.href = "/cs"
              }
              else {
                window.location.href = "{% url 'home' %}";
              }
            };
          </script>
        </div>
        <br><br>

        <form method="post">

          {% bootstrap_form_errors form type='non_fields' %}
          {% csrf_token %}

          <div class="field">
            {% bootstrap_field form.new_password layout='vertical' size='sm' %}
          </div>

          <div class="field">
            {% bootstrap_field form.confirm_password layout='vertical' size='sm' %}
          </div>

          {% if survey_type == 'DEPT-REGION-SITE' %}

          {{ form.dept_names.errors }}
          <div class="field">
            {% bootstrap_field form.dept_names layout='vertical' size='sm' %}
          </div>

          {{ form.region_names.errors }}
          <div class="field">
            {% bootstrap_field form.region_names layout='vertical' size='sm' %}
          </div>

          {{ form.site_names.errors }}
          <div class="field">
            {% bootstrap_field form.site_names layout='vertical' size='sm' %}
          </div>

         {% endif %}<br>

          <div class="field">
            {% buttons %}
              {% bootstrap_button "Create" button_type="submit" button_class="btn-primary" %}
            {% endbuttons %}
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

teamtemp/templates/password.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}Log in{% endblock %}

{% block body %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3" align="center">
        <h1>Enter the admin password</h1>
        <p></p>
        <div class="row">
          <form method="post">
            <div class="form-group">
              {% csrf_token %}
              {{ form.password.errors }}
              <div class="field">
                <label for="id_score">Admin password:</label>
                {{ form.password }}
              </div>
            </div>
            <div class="form-group">
              {% buttons %}
                {% bootstrap_button "Submit" button_type="submit" button_class="btn-primary" %}<br/>
                <a href="{% url "super" survey_id=survey_id redirect_to=redirect_to %}" class="btn">•</a>
              {% endbuttons %}
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

teamtemp/templates/set.html
{% extends "base.html" %}

{% block form_extra_head %}
  {{ form.media }}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.min.css">
  <script src="//code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
{% endblock %}

{% load bootstrap3 %}

{% block title %}Settings {{ survey.id }}{% endblock %}

{% block body %}

  <div class="container">

    <div class="row">
      <div class="col-md-12"><br>
        <BR>
        <div class="btn-group no-print" role="group" aria-label="nav">
          <a href="{% url 'admin' survey_id=survey.id %}" class="btn btn-info" role="button">ADMIN</a>
        </div>

        <BR><BR>

        <h1>Team Temperature</h1>
        <h2>Survey Settings</h2>
        <form method="post" autocomplete="off">
          {% csrf_token %}
          <input type="hidden" name="id" value="{{ survey.id }}"/>

          {{ form.survey_type.errors }}
          <div class="field">
            <label for="id_survey_type">Survey Type:</label><br/>
            {{ form.survey_type }} (<em>Team Temperature Survey</em>, <em>Customer Feedback Survey</em>, or
            <em>Department-Region-Site Temperature Survey</em> - aggregate results across Departments, Regions and Sites or office locations)
          </div>

          {{ form.max_word_count.errors }}
          <div class="field">
            <label for="id_max_word_count">Max Word Count:</label><br/>
            {{ form.max_word_count }} (Number of words accepted along with team temperature submission - Default: 1)
          </div>

          {% if survey.survey_type == 'DEPT-REGION-SITE' %}
              {{ form.dept_names.errors }}
              <div class="field">
                <label for="id_dept_names">Department Names:</label><br/>
                {{ form.dept_names }} (Comma separated list of department names for new teams when Survey Type is
                DEPT-REGION-SITE)
              </div>

              {{ form.region_names.errors }}
              <div class="field">
                <label for="id_region_names">Region Names:</label><br/>
                {{ form.region_names }} (Comma separated list of region names for new teams when Survey Type is
                DEPT-REGION-SITE)
              </div>

              {{ form.site_names.errors }}
              <div class="field">
                <label for="id_site_names">Site Names:</label><br/>
                {{ form.site_names }} (Comma separated list of Site names for new teams when Survey Type is
                DEPT-REGION-SITE)
              </div>
          {% endif %}

          {{ form.archive_schedule.errors }}
          <div class="field">
            <label for="id_archive_schedule">Archive Interval:</label><br/>
            {{ form.archive_schedule }} (Number of days. 0 to disable automated archive.)
          </div>

          {{ form.next_archive_date.errors }}
          <div class="field">
            <label for="id_next_archive_date">Next Archive Date:</label><br/>
            <div class="next_archive_date">{{ form.next_archive_date }}</div> (Date of next automated archive)
          </div>

          {{ form.new_password.errors }}
          <div class="field">
            <label for="id_password">Change Survey Password:</label><br/>
            {{ form.new_password }} (Leave blank to retain existing password)
          </div>

          {{ form.confirm_password.errors }}
          <div class="field">
            <label for="id_confirm_password">Confirm Survey Password:</label><br/>
            {{ form.confirm_password }} (Leave blank to retain existing password)
          </div>

          {{ form.default_tz.errors }}
          <div class="field">
            <label for="id_default_tz">Default Timezone:</label><br/>
            {{ form.default_tz }} (pytz.all_timezones)
          </div>

          <h3>Team Name Change</h3>
          {% for team in survey_teams %}
            {{ team.team_name }}<BR>
          {% endfor %}
          <BR>
          {{ form.current_team_name.errors }}
          <div class="field">
            <label for="id_current_team_name">Current team name:</label><br/>
            {{ form.current_team_name }} (Check for trailing spaces if name change fails)
          </div>
          {{ form.new_team_name.errors }}
          <div class="field">
            <label for="id_new_team_name">New team name:</label><br/>
            {{ form.new_team_name }} (Blank will delete all team records)
          </div>
          {{ form.censored_word.errors }}
          <div class="field">
            <label for="id_censored_word">Censor Word:</label><br/>
            {{ form.censored_word }} (ALL occurrences will be removed from this survey)
          </div>

          <br><br>
          <input type="submit" value="Submit"/>
        </form>
      </div>
    </div>
  </div>
  <script>
  $( function() {
      $('.datepicker').datepicker({dateFormat: 'yy-mm-dd'});
  } );
  </script>
{% endblock %}